name: block_oni_app
description: "Block Oni - Flutter × Unity Board Game"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # =========================
  # 状態管理
  # =========================
  provider: ^6.1.2

  # =========================
  # 永続化
  # =========================
  shared_preferences: ^2.2.2

  # =========================
  # Socket通信
  # =========================
  socket_io_client: ^2.0.3+1

  # =========================
  # Unity連携（Desktop / Android / iOS）
  # ※ Web非対応
  # =========================
  flutter_unity_widget:
    git:
      url: https://github.com/juicycleff/flutter-unity-view-widget.git
      ref: master

  # UI Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
